#!/bin/bash

set -e

SOURCE_DIR="$(dirname $(realpath $0))"
TARGET_DIR="${SOURCE_DIR}/../lunkwill_build"
RM=true

if [[ $1 == "keep"  ]]
then
	RM=false
	shift
fi

if ${RM}
then
	rm -rf ${TARGET_DIR}
fi
mkdir -p ${TARGET_DIR}
cd ${TARGET_DIR}

${SOURCE_DIR}/configure


case $1 in

	"dbg")
		shift
		make -j9;
		bash -c "gdb ./lunkwill -ex 'set follow-fork-mode child' $@"
	;;
	"mem")
		shift
		make -j9;
		bash -c "valgrind --num-callers=50 --leak-resolution=high --leak-check=full --track-origins=yes --show-reachable=yes --show-possibly-lost=yes --trace-children=yes --time-stamp=yes ./lunkwill $@"
	;;
	"run")
		shift
		make -j9;
		clear;
		bash -c "./lunkwill $@"
	;;
	"doc")
		cd ${SOURCE_DIR}
		mkdir -p docs

		(cat scripts/doxyfile; \
		 echo "EXCLUDE = 04-plugins" )| doxygen -

		for i in $(ls ./04-plugins/);
		do
			cat scripts/doxyfile | sed -e \
			"s#OUTPUT_DIRECTORY       = docs/lunkwill#OUTPUT_DIRECTORY       = docs/$i#" \
			| sed -e \
				"s#INPUT                  = .#INPUT                  = ./04-plugins/$i#" \
			| doxygen -
		done

		rm -f ./docs/index.html
		for i in $(ls ./docs/);
		do
			echo "<a href='./$i/html/index.html'>$i</a><br>">>./docs/index.html
		done
	;;

	"clang")
		CC=clang make -j9
		bash
	;;
	
	"gcc")
		YUI="~/.bin/yui.jar" make -j9;
		bash
	;;
	
	"travis")
		make -j99
		./lunkwill -f
		sleep 2
		
		../lunkwill/scripts/lunkwill_tests.sh travis
	;;

	"astyle")
		cd ${SOURCE_DIR}
		astyle -nUt --style=ansi --recursive *.c *.h
	;;

	*)
		echo $@
		bash
esac

if ${RM}
then
	rm -rf ${TARGET_DIR}
fi

