#!/bin/bash

TARGET_DIR=$(dirname $0)

rm -rf ${TARGET_DIR}/build
mkdir ${TARGET_DIR}/build
cd ${TARGET_DIR}/build

../configure
make -j9
bash -c "valgrind --leak-check=full --show-reachable=yes --show-possibly-lost=yes --trace-children=yes --time-stamp=yes ./lunkwill || ./lunkwill"
rm -rf ${TARGET_DIR}/build
